# 1 - Uncomment the lines below you want to change by removing the # in the beginning

# 2 - A list of devices you want to take the screenshots from
 devices([
   "iPhone X"
 ])

 languages([
   "en-US",
   "fr-Fr"
 ])

# 3 - The name of the scheme which contains the Tests
scheme("XebiaAssignmentTests")

# 4 - The name of the scheme which contains the UI Tests
scheme("XebiaAssignmentUITests")

# 5 - Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# 6 - remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)
